server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://3.38.163.13:5432/inventorydb
    username: postgres
    password: StrongP@ssw0rd
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc.time_zone: Asia/Seoul
        format_sql: true
        show_sql: true
