server:
  port: 8080

spring:
    datasource:
      url: jdbc:postgresql://3.38.163.13:5432/orderdb
      username: postgres
      password: StrongP@ssw0rd
    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          jdbc.time_zone: Asia/Seoul
          format_sql: true
      show-sql: true

clients:
  inventory:
    base-url: http://54.181.0.55:8081
